### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by axionl**
Add qv2ray-dev-git for the developer.

### CODE REVIEW

**Comment by lhy0403** [comment]
Can one of the admins verify this patch?

**Comment by axionl** [comment]
> Can one of the admins verify this patch?

I modify the default configuration path to `~/.config/qv2ray` or `~/.config/qv2ray-debug` for the AUR repository which just my personal preference. This is not necessary but also does not affect the development of the others.

**Comment by lhy0403** [comment]
> > Can one of the admins verify this patch?
> 
> I modify the default configuration path to `~/.config/qv2ray` or `~/.config/qv2ray-debug` for the AUR repository which just my personal preference. This is not necessary but also does not affect the development of the others.

Yes, Linux users can do such things.

**Comment by aliyuchang33** [comment]
test this please

**Comment by lhy0403** [comment]
Why the CI is still not finished????

**Comment by lhy0403** [comment]
test-build-needed

**Pull request merged**
