### PR TITLE
Added connection statistics.

### PR DESCRIPTION
**Pull request by lhy0403**
This is still not ready to merge, all CIs may fail due to a lack of gRPC package.

### CODE REVIEW

**Comment by lhy0403** [comment]
ALL CI failed!
See #69 for more details.
(That's actually what I have expected)

**Comment by aliyuchang33** [comment]
lol

**Comment by lhy0403** [comment]
We'll temporarily disable this function on Windows platform as it's so f**kin difficult to implement.

**Comment by lhy0403** [comment]
I'll drop computer science if this build failed.

**Pull request merged**
