### PR TITLE
[VD][WIP] #130 Change to a new logo, new icon color schemes and added dark mode support

### PR DESCRIPTION
**Pull request by lhy0403**
Please see #130 for more information.

To Assignees: Please verify if the new UI is suitable for users, by considering if the contents will make confusion.

### CODE REVIEW

**Comment by lhy0403** [comment]
[WIP] I'm currently working on this branch and do not merge it yet! Thanks.

**Comment by axionl** [comment]
> Please see #130 for more information.
> 
> To Assignees: Please verify if the new UI is suitable for users, by considering if the contents will make confusion.

The description is missing for `Ping` and `Share` buttons.

**Comment by lhy0403** [comment]
gotit

**Comment by lhy0403** [comment]
@axionl Changes made, please review if there's anything else to do before merge to the `dev` branch.
Thanks

**Pull request merged**
