### PR TITLE
Qv2ray v2 Alpha 1.1

### PR DESCRIPTION
**Pull request by lhy0403**

### CODE REVIEW

**Comment by lhy0403** [comment]
Upstream bug blocking us to check the build....
https://github.com/jurplel/install-qt-action/issues/14

**Comment by lhy0403** [comment]
PR Comment Test

**Comment by lhy0403** [comment]
We cannot merge this PR UNTIL upstream build is fixed, jurplel/install-qt-action#14

**Comment by lhy0403** [comment]
Will merge this PR after Github Action passed.

**Comment by lhy0403** [comment]
Welcome to the Qv2ray v2 Alpha 1.1

**Comment by DuckSoft** [comment]
@lhy0403 don't forget to update the documentation before releasing

**Comment by lhy0403** [comment]
Well there's no document EXCEPT the `config_version` change....
Will construct final documentation before final v2 release

**Pull request merged**
